const countries = [
    'Afganistan',
    'Arnavutluk',
    'Cezayir',
    'Andora',
    'Angola',
    'Antigua ve Barbuda',
    'Arjantin',
    'Ermenistan',
    'Avustralya',
    'Avusturya',
    'Azerbaycan',
    'Bahamalar',
    'Bahreyn',
    'Bangladeş',
    'Barbados',
    'Beyaz Rusya',
    'Belçika',
    'Beliz',
    'Ben',
    'Butan',
    'Bolivya',
    'Bosna Hersek',
    'Botsvana',
    'Brezilya',
    'Bruney',
    'Bulgaristan',
    'Burkina Faso',
    'Burundi',
    'Kamboçya',
    'Kamerun',
    'Kanada',
    'Cape Verde',
    'Orta Afrika Cumhuriyeti',
    'Çad',
    'Şili',
    'Çin',
    'Kolombiya',
    'Komorlar',
    'Kongo (Brazzaville)',
    'Kongo',
    'Kosta Rika',
    "Fildişi Sahili",
    'Hırvatistan ',
    'Küba',
    'Kıbrıs',
    'Çek Cumhuriyeti',
    'Danimarka',
    'Cibuti',
    'Dominika',
    'Dominik Cumhuriyeti',
    'Doğu Timor (Timor Timur)',
    'Ekvador',
    'Mısır',
    'El Salvador',
    'Ekvator Ginesi',
    'Eritre',
    'Estonya',
    'Etiyopya',
    'Fiji',
    'Finlandiya',
    'Fransa',
    'Gabon',
    'Gambiya',
    'Gürcistan',
    'Almanya',
    'Gana',
    'Yunanistan',
    'Grena',
    'Guatemala',
    'Gine',
    'Gine-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Macaristan',
    'İzlanda',
    'Hindistan',
    'Endonezya',
    'İran',
    'Irak',
    'İrlanda',
    'İsrail',
    'İtalya',
    'Jamaika',
    'Japonya',
    'Ürdün',
    'Kazakistan',
    'Kenya',
    'Kirbati',
    'Kore, Kuzey',
    'Kore, Güney',
    'Kuveyt',
    'Kırgızistan',
    'Laos',
    'Letonya',
    'Lübnan',
    'Lezoto',
    'Liberya',
    'Libya',
    'Lihtenştayn',
    'Litvanya',
    'Lüksemburg',
    'Makedonya',
    'Madagaskar',
    'Malavi',
    'Malezya',
    'Maldivler',
    'Mali',
    'Malta',
    'Marshall Adaları',
    'Moritanya',
    'Mauritius',
    'Meksika',
    'Mikronezya',
    'Moldova',
    'Monako',
    'Moğolistan',
    'Fas',
    'Mozambik',
    'Myanmar',
    'Namibya',
    'Nauru',
    'Nepal',
    'Hollanda',
    'Yeni Zelanda',
    'Nikaragua',
    'Nijer',
    'Nijerya',
    'Norveç',
    'Umman',
    'Pakistan',
    'Pala',
    'Panama',
    'Papua Yeni Gine',
    'Paraguay',
    'Peru',
    'Filipinler',
    'Polonya',
    'Portekiz',
    'Katar',
    'Romanya',
    'Rusya',
    'Ruanda',
    'Aziz Kitts ve Nevis',
    'Aziz Lucia',
    'Aziz Vincent',
    'Samoa',
    'San Marino',
    'Sao Tome ve Principe',
    'Suudi Arabistan',
    'Senegal',
    'Sırbistan ve Karadağ',
    'Seyşeller',
    'Sierra Leone',
    'Singapur',
    'Slovakya',
    'Slovenya',
    'Süleyman Adaları',
    'Somali',
    'Güney Afrika',
    'İspanya',
    'Sri Lanka',
    'Sudan',
    'Surinam',
    'Svaziland',
    'İsveç',
    'İsviçre',
    'Suriye',
    'Tayvan',
    'Tacikistan',
    'Tanzanya',
    'Tayland',
    'Git',
    'Tanga',
    'Trinidad ve Tobago',
    'Tunus',
    'Türkiye',
    'Türkmenistan',
    'Tuval',
    'Uganda',
    'Ukrayna',
    'Birleşik Arap Emirlikleri',
    'Birleşik Krallık',
    'Amerika Birleşik Devletleri',
    'Uruguay',
    'Özbekistan',
    'Vanuatu',
    'Vatikan Şehri',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambiya',
    'Zimbabve'
];


let panel = document.querySelector(".countries-wrapper");

for (let index = 0; index < countries.length; index++) {


    const divCountry = document.createElement('div');
    const paraf = document.createElement('p');


    countries[index] = countries[index].toUpperCase();

    paraf.innerHTML = countries[index];
    divCountry.appendChild(paraf);
    panel.appendChild(divCountry);
}

let totalCountries = document.querySelector("#total-countries");
totalCountries.textContent = `Total Number of countries: ${countries.length}`